package com.aiexpenseledger.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.Date;
import java.util.Optional;

@Component
public class JwtTokenProvider {

    private static final Logger log = LoggerFactory.getLogger(JwtTokenProvider.class);
    private static final String ISSUER = "ai-expense-ledger";
    private static final String EMAIL_CLAIM = "email";

    private final SecretKey signingKey;
    private final JwtProperties properties;

    public JwtTokenProvider(JwtProperties properties) {
        this.properties = properties;
        this.signingKey = resolveKey(properties.secret());
    }

    public String generateToken(Long userId, String email) {
        Instant now = Instant.now();
        return Jwts.builder()
                .issuer(ISSUER)
                .subject(String.valueOf(userId))
                .claim(EMAIL_CLAIM, email)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plus(properties.expiration())))
                .signWith(signingKey)
                .compact();
    }

    /** Returns the user encoded in a valid, unexpired token signed by this server; empty otherwise. */
    public Optional<AuthenticatedUser> parseToken(String token) {
        try {
            Claims claims = Jwts.parser()
                    .verifyWith(signingKey)
                    .requireIssuer(ISSUER)
                    .build()
                    .parseSignedClaims(token)
                    .getPayload();
            return Optional.of(new AuthenticatedUser(
                    Long.valueOf(claims.getSubject()),
                    claims.get(EMAIL_CLAIM, String.class)));
        } catch (JwtException | IllegalArgumentException e) {
            log.debug("Rejected JWT: {}", e.getMessage());
            return Optional.empty();
        }
    }

    public long getExpirationSeconds() {
        return properties.expiration().toSeconds();
    }

    /**
     * Accepts a Base64 secret of at least 32 bytes, or any other string of at least 32 characters
     * (as generated by hosting platforms), which is hashed with SHA-256 into a 256-bit key.
     */
    private static SecretKey resolveKey(String secret) {
        if (!StringUtils.hasText(secret)) {
            log.warn("app.jwt.secret (JWT_SECRET) is not set; using an ephemeral signing key. "
                    + "Issued tokens will be invalidated on restart. Set JWT_SECRET in production.");
            return Jwts.SIG.HS256.key().build();
        }
        try {
            byte[] decoded = Decoders.BASE64.decode(secret.trim());
            if (decoded.length >= 32) {
                return Keys.hmacShaKeyFor(decoded);
            }
        } catch (RuntimeException notBase64) {
            // Fall through to treating the secret as a passphrase.
        }
        if (secret.trim().length() < 32) {
            throw new IllegalStateException("app.jwt.secret must be at least 32 characters (or 32 Base64-decoded bytes)");
        }
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(secret.trim().getBytes(StandardCharsets.UTF_8));
            return Keys.hmacShaKeyFor(digest);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is unavailable", e);
        }
    }
}
